package com.thebrokenrail.herobrine.item;

import com.thebrokenrail.herobrine.HerobrineRewoven;
import net.minecraft.client.item.TooltipContext;
import net.minecraft.item.Item;
import net.minecraft.item.ItemGroup;
import net.minecraft.item.ItemStack;
import net.minecraft.text.Text;
import net.minecraft.text.TranslatableText;
import net.minecraft.util.Formatting;
import net.minecraft.util.Rarity;
import net.minecraft.world.World;

import java.util.List;

public class BlackDiamondItem extends Item {
    public BlackDiamondItem() {
        super(new Settings().group(ItemGroup.MISC).maxCount(1).rarity(Rarity.RARE).fireproof());
    }

    @Override
    public void appendTooltip(ItemStack stack, World world, List<Text> tooltip, TooltipContext context) {
        super.appendTooltip(stack, world, tooltip, context);
        tooltip.add(new TranslatableText("item." + HerobrineRewoven.NAMESPACE + ".black_diamond.tooltip.1").formatted(Formatting.GRAY).formatted(Formatting.ITALIC));
        tooltip.add(new TranslatableText("item." + HerobrineRewoven.NAMESPACE + ".black_diamond.tooltip.2").formatted(Formatting.GRAY).formatted(Formatting.ITALIC));
    }
}
