package com.thebrokenrail.herobrine.client;

import com.thebrokenrail.herobrine.HerobrineRewoven;
import com.thebrokenrail.herobrine.client.entity.HerobrineEntityRenderer;
import net.fabricmc.api.ClientModInitializer;
import net.fabricmc.api.EnvType;
import net.fabricmc.api.Environment;
import net.fabricmc.fabric.api.client.rendereregistry.v1.EntityRendererRegistry;

@Environment(EnvType.CLIENT)
public class HerobrineRewovenClient implements ClientModInitializer {
    @Override
    public void onInitializeClient() {
        EntityRendererRegistry.INSTANCE.register(HerobrineRewoven.HEROBRINE_ENTITY_TYPE, (entityRenderDispatcher, context) -> new HerobrineEntityRenderer(entityRenderDispatcher));
    }
}
